server {
    listen 80;

    # React Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Identity Service
    location /api/v1/auth/ {
        proxy_pass http://identity-service:8081;
    }

    location /api/v1/admin/ {
        proxy_pass http://identity-service:8081;
    }

    location /api/v1/colleges/ {
        proxy_pass http://identity-service:8081;
    }

    location /api/v1/users/ {
        proxy_pass http://identity-service:8081;
    }

    # Academic Service
    location /api/v1/academic/ {
        proxy_pass http://academic-service:8082;
    }

    location /api/v1/attendance/ {
        proxy_pass http://academic-service:8082;
    }

    location /api/v1/sections/ {
        proxy_pass http://academic-service:8082;
    }

    location /api/v1/subjects/ {
        proxy_pass http://academic-service:8082;
    }

    location /api/v1/blocks/ {
        proxy_pass http://academic-service:8082;
    }

    # Placement Service
    location /api/v1/placement/ {
        proxy_pass http://placement-service:8083;
    }

    # Static Assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
        root /usr/share/nginx/html;
    }
}